version: '3.8'

services:
  
  web:
    container_name: higo
    build:
      context: ./project
      dockerfile: Dockerfile
    volumes:
      - ./project:/usr/src/app
    ports:
      - 8004:8000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@higo_db:5432/higo
    depends_on:
      - db
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
  
  db:
    hostname: higo_db
    container_name: higo_db
    image: postgres:13.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: higo