"""Changes on model relations to generate correct dependencies

Revision ID: 0a68afa491a7
Revises: eeded4b66e9b
Create Date: 2022-03-13 15:48:36.048577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a68afa491a7'
down_revision = 'eeded4b66e9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
