"""New migration

Revision ID: 1ac4322436b6
Revises: 63bf8942311f
Create Date: 2022-03-13 20:07:54.513280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ac4322436b6'
down_revision = '63bf8942311f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
