"""Initial database conf

Revision ID: 8795811c007a
Revises: b7ebe3d2b9ad
Create Date: 2022-03-13 17:04:57.806579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8795811c007a'
down_revision = 'b7ebe3d2b9ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
