"""Changes on model relations to generate correct dependencies

Revision ID: aab39c21d288
Revises: 0a68afa491a7
Create Date: 2022-03-13 15:49:46.181774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aab39c21d288'
down_revision = '0a68afa491a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
